Repository mobile-dev-16/flutter_app, pull requests merged in 2024-10, with the labels that each got.

#30 feature/implement-firebase-#28
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/eco_bites/MainActivity.kt
  android/settings.gradle
  firebase.json
  lib/firebase_options.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  widgetbook/macos/Flutter/GeneratedPluginRegistrant.swift
  widgetbook/pubspec.lock
Labels: enhancement

#33 Fixes. feature/firebase-authentication-#31
  lib/features/auth/presentation/screens/login_screen.dart
  lib/features/auth/presentation/screens/register_screen.dart
Labels: bug

#38 Resolves. feature/gps-location-selecter-#35
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  android/gradle.properties
  android/settings.gradle
  lib/app.dart
  lib/core/utils/request_util.dart
  lib/core/utils/reverse_geocoding.dart
  lib/features/address/domain/address.dart
  lib/features/address/presentation/bloc/address_bloc.dart
  lib/features/address/presentation/bloc/address_event.dart
  lib/features/address/presentation/bloc/address_state.dart
  lib/features/address/presentation/screens/address_detail_screen.dart
  lib/features/address/presentation/screens/address_screen.dart
  lib/features/address/repository/address_repository.dart
  lib/features/home/presentation/screens/home_screen.dart
  pubspec.lock
  pubspec.yaml
  widgetbook/macos/Flutter/GeneratedPluginRegistrant.swift
  widgetbook/pubspec.lock
Labels: enhancement

#42 Fix/better gps addres selector #36
  .github/workflows/dart.yml
  .gitignore
  .vscode/settings.json
  lib/core/ui/layouts/main_layout.dart
  lib/core/utils/user_util.dart
  lib/features/address/domain/address.dart
  lib/features/address/domain/models/address.dart
  lib/features/address/presentation/bloc/address_bloc.dart
  lib/features/address/presentation/bloc/address_event.dart
  lib/features/address/presentation/bloc/address_state.dart
  lib/features/address/presentation/screens/address_detail_screen.dart
  lib/features/address/presentation/screens/address_screen.dart
  lib/features/address/repository/address_repository.dart
  lib/features/auth/presentation/bloc/auth_bloc.dart
  lib/features/home/presentation/screens/home_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#47 Resolves. feature/firebase-monitoring-performance-#46
  lib/app.dart
  lib/core/ui/layouts/main_layout.dart
  lib/features/home/presentation/screens/home_screen.dart
  lib/features/splash/presentation/screens/splash_screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  widgetbook/lib/core/ui/layouts/main_layout.dart
  widgetbook/lib/features/home/presentation/screens/home_screen.dart
  widgetbook/lib/features/splash/presentation/screens/splash_screen.dart
Labels: enhancement

#45 Feature/for you
  lib/features/food/domain/models/cuisine_type.dart
  lib/features/food/domain/models/food_business.dart
  lib/features/food/domain/models/offer.dart
  lib/features/food/domain/models/offer_type.dart
  lib/features/food/presentation/bloc/food_business_bloc.dart
  lib/features/food/presentation/bloc/food_business_event.dart
  lib/features/food/presentation/bloc/food_business_state.dart
  lib/features/food/repository/food_business_repository.dart
  lib/features/home/presentation/screens/home_screen.dart
  lib/features/home/presentation/widgets/for_you_tab.dart
  lib/main.dart
Labels: enhancement

#48 Fix/build error
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/features/address/presentation/bloc/address_bloc.dart
  lib/features/auth/repository/auth_repository.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug
